GradienceTeam/Gradience

.github/workflows/black.yml

ci: add black format

---

Makefile
local.sh
meson.build
src/__init__.py
src/builtin_preset_row.py
src/constants.py.in
src/main.py
src/meson.build
src/modules/__init__.py
src/modules/utils.py
src/plugin_row.py
src/plugins_list.py
src/preset_row.py
src/run_async.py
src/welcome.py
src/window.py

- Create `buglog` function,
- Move `to_slug_case` and `buglog` to `modules/utils.py`,
- Replace print() with buglog(),
- Fix error toast showing up on startup when build in Flatpak,
- Update BUGTRACKER_URL and TRANSLATE_URL to the corrent ones,
- Add variables from meson.build to constants.py.in config,
- Show tooltip when focused on `monet_file_chooser_button`,
- Update copyright info in window.py and add in plugin_row.py,
- Update local.sh and Makefile,
- Fix typo in translator_credits,
- Add tfuxu in translator credits

A bunch of improvements

---

pylintrc

feat: improve pylint style

---

data/ui/window.blp
src/main.py

Instead of just overwriting `gtk.css` with a new `gtk.css` when applying the theme, we write the current contents of `gtk.css` to `gtk.css.bak` then write apply our changes to `gtk.css`

Implement backup functionality for gtk.css

---

data/ui/custom_css_group.blp

Just a quick UI change to 'Custom CSS' TextView in Advanced tab.
<br>
Without margins:
With margins:

Add margins to 'Custom CSS' TextView

---

data/ui/presets_manager_window.blp
src/builtin_preset_row.py
src/modules/custom_presets.py
src/modules/utils.py
src/preset_row.py
src/presets_manager_window.py

- Make `presets_manager_window` more readable, by moving some code into new functions,
- Always clear `search_results_list` to avoid Gtk warnings about non-child objects,
- Remove duplicate toast, that was showing up, when removing a preset,
- Add more `try ... except` statements to `custom_presets` module for easier debugging,
- Convert more print() functions to buglog(), and fix exception messages not showing up in `preset_row.py`,
- Fix `preset_empty` ActionRow not showing when user doesn't have any presets

Preset window improvements

---

data/ui/welcome.blp

Trim unnecessary phrasing in accordance with HIG and fix comma splice
- Removed unnecessary verbage ("please note", "in some situations")
- Fixed comma splice

Change welcome warning to be HIG-compliant

---

data/ui/welcome.blp

As "I agree" is an odd way to signal acknowledgement of a warning, change button text to the more standard "Ok".
- Changed warning button text to "Ok"

fix: change button text on warning

---

build-aux/flatpak/com.github.GradienceTeam.Gradience.Devel.json
build-aux/flatpak/com.github.GradienceTeam.Gradience.json

This PR makes a couple of corrections into upstream Flatpak manifests to make them more Flathub compliant (less work for Flathub packages maintainer and improved compile performance), ~~and adds a fix for issue #612~~ (added in a8a1df74b2a283446869a31338b9d6be6bdf0a30).

Sync upstream manifests with Flathub manifests

---

data/plugins/firefox_gnome_theme.py

The old code would incorrectly iterate over files (such as the profiles.ini file) which would trigger an exception and skip the entire firefox installation.  This checks the path to ensure it is a directory (and thus a profile) before trying to open the customChrome.css file for writing.  It correctly themes my Librefox now.
- Fixed path iteration

Firefox theme plugin:  correctly parse installations with multipe profiles

---

gradience/backend/flatpak_overrides.py
gradience/backend/logger.py
gradience/backend/models/preset.py
gradience/backend/preset_downloader.py
gradience/backend/theming/monet.py
gradience/backend/theming/preset_utils.py
gradience/frontend/cli/cli.in
gradience/frontend/main.py
gradience/frontend/utils/run_async.py
gradience/frontend/views/main_window.py
gradience/frontend/views/presets_manager_window.py
gradience/frontend/widgets/explore_preset_row.py
gradience/frontend/widgets/preset_row.py

This PR adds exception information for logger messages, for use mostly in backend modules.
```
[Gradience] ERROR: An error occurred while generating a Monet palette.
Exc: cannot identify image file 'FILE'
At: /PATH/gradience/backend/theming/monet.py:49
/PATH/venv/lib/python3.10/site-packages/PIL/Image.py:3186
```
- Added new `set_exc_info` internal function in `backend/logger` module to insert exception information into logger messages,
- Updated logger messages to utilize new `exc` option
~**I still need to check a few things, so this isn't yet fully tested.**~

Exception information for logging facility

---

.github/workflows/build.yml

since it's only doing build, we can call it build :)
Signed-off-by: 0xMRTT <0xMRTT@proton.me>
Fixes #(issue)
- Fixed …
- Added …

feat: rename ci to build

---

gradience/backend/theming/preset_utils.py
gradience/backend/utils/colors.py
gradience/frontend/widgets/option_row.py

This PR enforces on Gradience usage of hexadecimal format in most places, unless alpha channel is specified.
The enforcement of hex format is only on Gradience itself, users still can use RGB and standard web CSS color names.
Probably Fixes #666 
- Created new `rgb_to_hash` function,
- Made `argb_to_color_code` function usable,
- Enforced HEX format on Monet generated variables and ColorButtons in variables rows

Use hexadecimal format unless alpha channel is specified

---

gradience/frontend/dialogs/save_dialog.py
gradience/frontend/main.py
gradience/frontend/widgets/builtin_preset_row.py
gradience/frontend/widgets/preset_row.py

This PR reuses `You have unsaved changes!` dialog when an currently preset isn't yet saved and user clicks to load another preset. The implementation uses internal `is_dirty` check to determine either to show or immediately load a preset.
Fixes #665
- Extracted `show_unsaved_dialog` function into two smaller functions
- Made `on_save_preset_entry_change` function accessible in external modules
- Changed `save_preset` function name to `on_save_dialog_response`
- Added mechanisms to show unsaved dialog in Preset Manager and when using quick preset switcher

Show `Unsaved preset` dialog when switching to other preset

---

data/ui/window.blp

I added mnemonics to the labels that switch pages: "Colors",
"Monet" and "Advanced".
Still need to translate this feature to others languages
and I'd be glad to do that to Brazilian Portuguese. :)
- Added
- mnemonics to labels in initial page: "Colors", "Monet" and "Advanced" 
To use this feature, you just need to press "alt" and it should highlight with an underline the options of mnemonics with shortcuts.
Than press the letter underlined in the option you choose to access.

feat: add mnemonics to view switchers

---

gradience/backend/theming/preset_utils.py

Changed .onError to .onErrorContainer for Monet-generated error and destructive foreground colors. Using .onError results in unreadable color contrasts (i.e. white on pink, red on red)
Fixes #425
- Changed error and destructive foreground colors to .onErrorContainer

fix(preset_utils.py): Improve error/destructive contrasts

---

.github/workflows/build.yml

build.yml: bump flatpak builder version

---

data/ui/builtin_preset_row.blp
data/ui/explore_preset_row.blp
data/ui/monet_theming_group.blp
data/ui/option_row.blp
data/ui/plugin_row.blp
data/ui/shell_theming_group.blp
gradience/frontend/widgets/option_row.py

Sets the `activatable-widget` on ActionRows, allowing the user to click the row itself to activate the child widget. This brings it more inline with the default libadwaita ActionRows, e.g. ComboRow. It is only done for non-destructible actions. 
- Fixed clicking on rows to activate their children 
1. Open the app
2. Click on an ActionRow, e.g. an OptionRow
3. Notice how the ColorDialog is opened

feat: set activatable widget on action rows

---

data/ui/builtin_preset_row.blp
data/ui/explore_preset_row.blp
data/ui/monet_theming_group.blp
data/ui/option_row.blp
data/ui/plugin_row.blp
data/ui/shell_theming_group.blp
gradience/frontend/widgets/option_row.py

Changes the `text-value-toggle` tooltip-text to either display `Show Hex` or `Show Color` depending on which child is currently visible.
Depends on https://github.com/GradienceTeam/Gradience/pull/789
- Improved tooltip for toggling color values
1. Open the app
2. View tooltip of the `text-value-toggle` button
3. Click the `text-value-toggle ` button
4. Notice how the tooltip changes

feat: show text-value-toggle tooltip depending on visible value

---

build-aux/flatpak/com.github.GradienceTeam.Gradience.json
data/ui/app_type_dialog.blp
data/ui/builtin_preset_row.blp
data/ui/custom_css_group.blp
data/ui/error_list_row.blp
data/ui/explore_preset_row.blp
data/ui/log_out_dialog.blp
data/ui/monet_theming_group.blp
data/ui/no_plugin_window.blp
data/ui/option_row.blp
data/ui/palette_shades.blp
data/ui/plugin_row.blp
data/ui/preferences_window.blp
data/ui/preset_row.blp
data/ui/presets_manager_window.blp
data/ui/repo_row.blp
data/ui/reset_preset_group.blp
data/ui/save_dialog.blp
data/ui/share_window.blp
data/ui/shell_prefs_window.blp
data/ui/shell_theming_group.blp
data/ui/theming_empty_group.blp
data/ui/welcome_window.blp
data/ui/window.blp

Updates Blueprint UI definitions to 0.8.0 syntax, to get rid off those deprecation warnings.
- Updated UI definitions to Blueprint 0.8.0 syntax

Update UI definitions to Blueprint 0.8.0 syntax

---

gradience/backend/theming/shell.py

This PR refactors a few operations to make the code handle edge cases efficiently with marginal performance improvements.
- Stores the comma separated string representation of valid versions for later use in raising exceptions.
- Uses tuple for `async_data` in `ShellTheme` since its members are immutable.
- Uses tuple decomposition to assign theme variant and preset from `async_data` later.
- Replaces `Gio.File.make_directory_with_parents` with Python's builtin `os.makedirs` with `exist_ok` as True to implicitly create directories when nonexistent.
-  Instead of relying on `KeyError`s when accessing dictionary values, the `get` method is used to supply a default value.
- When a key might exist in one dictionary, the `get` method (which may return `None`) is coupled with the nullish `or` …

Refactor shell theming module

---

data/com.github.GradienceTeam.Gradience.appdata.xml.in.in

It appears that the appstream project no longer supports `translatable=no` properties, and gettext extract the `translatable=no` marked strings as translatable.
I opened an issue to inform about the situation, but `translatable=no` properties are not accepted by developers. You can find the issue here: `https://github.com/ximion/appstream/issues/623`
**Please test your script or string extraction process before merging this PR.**
> In MetaInfo files, each individual paragraph of a description
> (or enumerated entry) is translated individually, however,
> you can only exclude the complete block from being translated
> by adding `translate="no"` to the description element.
Source: https://freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html
Fixes #(issue) 
- Fixed …
- …

appdata: `translate=no` properties
