GradienceTeam/Gradience

src/main.py

i just noticed the changes to the icon i don't like them and i don't want my name associated with this icon anymore , thanks for understanding .

remove myself from the artists array

---

README.md

add actions badges

---

.github/CODEOWNERS

feat: update CODEOWNERS

---

.github/workflows/dependency-review.yml

ci: add dep review

---

.github/workflows/black.yml

ci: add-on push

---

.github/workflows/autopep8.yml

ci: add autopep8

---

.github/workflows/autopep8.yml

ci: remove reviewers

---

.github/workflows/flatpak.yml

ci: use Gradience

---

.github/workflows/autopep8.yml

ci: only run on main

---

po/POTFILES

fix: filename. change

---

data/com.github.GradienceTeam.Gradience.appdata.xml.in.in

Fix wallpaper
Signed-off-by: Sabri Ünal <libreajans@gmail.com>

Fix a typo

---

.github/workflows/autopep8.yml

CI: allow workflow_dispatch

---

.github/workflows/autopep8.yml

revert: ci autopep

---

.github/workflows/flatpak.yml

ci: add aarch64

---

data/com.github.GradienceTeam.Gradience.appdata.xml.in.in

fix: license metadata

---

po/LINGUAS
po/sv.po

Add Swedish Translation

---

README.md

feat: add flathub badge

---

data/com.github.GradienceTeam.Gradience.appdata.xml.in.in

release: 0.2.1

---

data/ui/welcome.blp

- Capitalize first letters in titles
- Use `activatable-widget` for switches
- Remove redundant whitespace

Minor UI improvements

---

src/presets_manager_window.py

_This is part of this: https://github.com/GradienceTeam/Community/pull/35_

feat: move presets to `next`

---

README.md

Global description
- Fixed ...
- Added ...
If applicable

merger `main` in `experements`

---

po/pl.po

Update Polish translations to include all new translatable text from new features, and modify some iffy translations to a more correct ones.

Update translations in Polish

---

data/ui/welcome.blp

- Fixed grammar of in-app changelog for this release

fix: correct grammar of in-app changelog

---

gradience/main.py
gradience/modules/flatpak_overrides.py
gradience/modules/preset.py
gradience/option.py
gradience/palette_shades.py
gradience/plugins_list.py
gradience/preset_row.py
gradience/presets_manager_window.py
gradience/setting.py
gradience/settings_schema.py
gradience/welcome.py
gradience/window.py

I attempted to make the Python files conform to the 79-character length limit as best I could. I didn't touch f strings and I didn't break up any HTML tags.

style: break up long lines

---

gradience/main.py
gradience/presets_manager_window.py

Written on github's editor, and not tested yet :sweat_smile: !

Solve preset directory issues

---

.editorconfig
data/ui/builtin_preset_row.blp
data/ui/error.blp
data/ui/explore_preset_row.blp
data/ui/no_plugin_pref.blp
data/ui/plugin_row.blp
data/ui/preferences.blp
data/ui/preset_row.blp
data/ui/presets_manager_window.blp
data/ui/repo_row.blp
data/ui/window.blp
gradience/preset_row.py
gradience/presets_manager_window.py

- set `intent_size` for *.blp in `editorconfig` to 2 spaces,
- change indentation in some .blp files to 2 spaces,
- add style class `flat` to buttons in `buildin_preset_row`

Change indentation in .blp files to 2 spaces

---

build-aux/flatpak/pypi-dependencies.json
po/zh_Hans.po

Signed-off-by: yangyangdaji <1504305527@qq.com>
fix typo

translate: Update (Chinese Simplified) Translation

---

gradience/main.py
gradience/modules/utils.py

- Fixed #573, #501 
- Added logout dialog after apply

feat: add logout (#573)

---

po/zh_Hans.po

Review Chinese Simplified translate
Signed-off-by: yangyangdaji <1504305527@qq.com>

Review Chinese Simplified translate

---

build-aux/flatpak/pypi-dependencies.json
gradience/main.py
gradience/utils/css.py
requirements.txt

This PR replaces `cssutils` module with a GTK CSS "parser" based on regex expressions.

Move from cssutils to a in-house solution

---

gradience/backend/flatpak_overrides.py
gradience/backend/logger.py
gradience/backend/meson.build
gradience/backend/models/preset.py
gradience/backend/preset_downloader.py
gradience/backend/utils/common.py
gradience/frontend/main.py
gradience/frontend/utils/run_async.py
gradience/frontend/views/main_window.py
gradience/frontend/views/plugins_list.py
gradience/frontend/views/preferences_window.py
gradience/frontend/views/presets_manager_window.py
gradience/frontend/views/share_window.py
gradience/frontend/views/welcome_window.py
gradience/frontend/widgets/builtin_preset_row.py
gradience/frontend/widgets/custom_css_group.py
gradience/frontend/widgets/explore_preset_row.py
gradience/frontend/widgets/plugin_row.py
gradience/frontend/widgets/preset_row.py

This PR introduces a new logger module and converts any log message that used `buglog()` before, to use one of five new functions from Logger class.
- Introduce new `backend/logger` facility
- Convert log messages from `buglog()` to a new Logger functions
Run Gradience in debug mode for the best experience.

Introduce new logging facility

---

HACKING.md
README.md
ROADMAP.md
SECURITY.md
requirements.txt

Some minor changes to the various things (cut version of #690)
- Removed hardcoded `anyascii` version as latest version is used automatically
- Some wording changes in markdown files

misc: minor improvements

---

data/com.github.GradienceTeam.Gradience.appdata.xml.in.in
gradience/frontend/views/about_window.py

Part of #712 
- Added release notes in appdata and about window

misc: Update release notes for 0.4 release

---

po/cs.po

Fixes #(issue) 
- Fixed …
- Added …

updated czech translation

---

.github/pull_request_template.md

Fixes various typos and improves the wording in the [pr-template](https://github.com/GradienceTeam/Gradience/blob/f2ae26c281772253681dbbe0832f988c8c7ca498/.github/pull_request_template.md).
Fixes #(issue) 
- Fixed typos in the pr template

chore(pr-template): fix typos

---

data/com.github.GradienceTeam.Gradience.gschema.xml.in
data/ui/preferences_window.blp
gradience/backend/globals.py
gradience/backend/preset_downloader.py
gradience/backend/utils/networking.py
gradience/frontend/cli/cli.in
gradience/frontend/main.py
gradience/frontend/views/preferences_window.py
gradience/frontend/views/presets_manager_window.py

fix: Typo with jsdelivr being jsdeliver

---

README.md

Added extra information about how to run Gradience on NixOS, and improved the grammar and clarity of the disclaimer about theming.

Change NixOS instructions and improve clarity of disclaimer.

---

data/com.github.GradienceTeam.Gradience.appdata.xml.in.in
data/com.github.GradienceTeam.Gradience.desktop.in.in

- Add vcs-browser URL
- Remove one of Purism tag to pass appstreamcli validation
- Remove categories and keywords that provided by the desktop file
- Sync keywords and categories with the desktop file
More information: https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/#icons-and-categories

appdata: Update appdata
